# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'blueprint.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1010, 795)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = PlotWidget(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(230, 10, 771, 471))
        self.graphicsView.setObjectName("graphicsView")
        self.btn = QtWidgets.QPushButton(self.centralwidget)
        self.btn.setGeometry(QtCore.QRect(30, 420, 181, 41))
        self.btn.setObjectName("btn")
        self.tab1 = QtWidgets.QTabWidget(self.centralwidget)
        self.tab1.setGeometry(QtCore.QRect(10, 490, 971, 271))
        self.tab1.setObjectName("tab1")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 261, 17))
        self.label_4.setObjectName("label_4")
        self.result_table = QtWidgets.QTableWidget(self.tab)
        self.result_table.setGeometry(QtCore.QRect(10, 50, 951, 181))
        self.result_table.setObjectName("result_table")
        self.result_table.setColumnCount(0)
        self.result_table.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.result_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.result_table.setVerticalHeaderItem(1, item)
        self.result_table.horizontalHeader().setMinimumSectionSize(57)
        self.result_table.verticalHeader().setDefaultSectionSize(57)
        self.tab1.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.result_table_2 = QtWidgets.QTableWidget(self.tab_2)
        self.result_table_2.setGeometry(QtCore.QRect(10, 50, 951, 181))
        self.result_table_2.setObjectName("result_table_2")
        self.result_table_2.setColumnCount(0)
        self.result_table_2.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.result_table_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.result_table_2.setVerticalHeaderItem(1, item)
        self.result_table_2.horizontalHeader().setMinimumSectionSize(57)
        self.result_table_2.verticalHeader().setDefaultSectionSize(57)
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(20, 20, 261, 17))
        self.label_5.setObjectName("label_5")
        self.tab1.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        self.label_6.setGeometry(QtCore.QRect(20, 20, 261, 17))
        self.label_6.setObjectName("label_6")
        self.result_table_3 = QtWidgets.QTableWidget(self.tab_3)
        self.result_table_3.setGeometry(QtCore.QRect(10, 50, 951, 181))
        self.result_table_3.setObjectName("result_table_3")
        self.result_table_3.setColumnCount(0)
        self.result_table_3.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.result_table_3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.result_table_3.setVerticalHeaderItem(1, item)
        self.result_table_3.horizontalHeader().setMinimumSectionSize(57)
        self.result_table_3.verticalHeader().setDefaultSectionSize(57)
        self.tab1.addTab(self.tab_3, "")
        self.tab2 = QtWidgets.QTabWidget(self.centralwidget)
        self.tab2.setGeometry(QtCore.QRect(10, 10, 201, 401))
        self.tab2.setObjectName("tab2")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.groupBox = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 181, 141))
        self.groupBox.setObjectName("groupBox")
        self.euler_method = QtWidgets.QRadioButton(self.groupBox)
        self.euler_method.setGeometry(QtCore.QRect(10, 20, 112, 23))
        self.euler_method.setChecked(True)
        self.euler_method.setObjectName("euler_method")
        self.ext_euler_method = QtWidgets.QRadioButton(self.groupBox)
        self.ext_euler_method.setGeometry(QtCore.QRect(10, 50, 112, 23))
        self.ext_euler_method.setObjectName("ext_euler_method")
        self.runge_kut_3_method = QtWidgets.QRadioButton(self.groupBox)
        self.runge_kut_3_method.setGeometry(QtCore.QRect(10, 80, 131, 23))
        self.runge_kut_3_method.setObjectName("runge_kut_3_method")
        self.runge_kut_4_method = QtWidgets.QRadioButton(self.groupBox)
        self.runge_kut_4_method.setGeometry(QtCore.QRect(10, 110, 131, 23))
        self.runge_kut_4_method.setObjectName("runge_kut_4_method")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 150, 181, 121))
        self.groupBox_2.setObjectName("groupBox_2")
        self.func_1 = QtWidgets.QRadioButton(self.groupBox_2)
        self.func_1.setGeometry(QtCore.QRect(10, 30, 161, 23))
        self.func_1.setChecked(True)
        self.func_1.setObjectName("func_1")
        self.func_2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.func_2.setGeometry(QtCore.QRect(10, 60, 141, 23))
        self.func_2.setObjectName("func_2")
        self.func_3 = QtWidgets.QRadioButton(self.groupBox_2)
        self.func_3.setGeometry(QtCore.QRect(10, 90, 112, 23))
        self.func_3.setObjectName("func_3")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab_4)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 280, 181, 81))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.accuracy_edit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.accuracy_edit.setObjectName("accuracy_edit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.accuracy_edit)
        self.start_edit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.start_edit.setObjectName("start_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.start_edit)
        self.end_edit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.end_edit.setObjectName("end_edit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.end_edit)
        self.tab2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 150, 181, 121))
        self.groupBox_3.setObjectName("groupBox_3")
        self.func_7 = QtWidgets.QRadioButton(self.groupBox_3)
        self.func_7.setGeometry(QtCore.QRect(10, 30, 161, 23))
        self.func_7.setChecked(False)
        self.func_7.setObjectName("func_7")
        self.func_8 = QtWidgets.QRadioButton(self.groupBox_3)
        self.func_8.setGeometry(QtCore.QRect(10, 60, 141, 23))
        self.func_8.setChecked(True)
        self.func_8.setObjectName("func_8")
        self.func_9 = QtWidgets.QRadioButton(self.groupBox_3)
        self.func_9.setGeometry(QtCore.QRect(10, 90, 112, 23))
        self.func_9.setObjectName("func_9")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 10, 181, 141))
        self.groupBox_4.setObjectName("groupBox_4")
        self.euler_method_3 = QtWidgets.QRadioButton(self.groupBox_4)
        self.euler_method_3.setGeometry(QtCore.QRect(10, 20, 112, 23))
        self.euler_method_3.setChecked(False)
        self.euler_method_3.setObjectName("euler_method_3")
        self.ext_euler_method_3 = QtWidgets.QRadioButton(self.groupBox_4)
        self.ext_euler_method_3.setGeometry(QtCore.QRect(10, 50, 112, 23))
        self.ext_euler_method_3.setChecked(True)
        self.ext_euler_method_3.setObjectName("ext_euler_method_3")
        self.runge_kut_3_method_3 = QtWidgets.QRadioButton(self.groupBox_4)
        self.runge_kut_3_method_3.setGeometry(QtCore.QRect(10, 80, 131, 23))
        self.runge_kut_3_method_3.setObjectName("runge_kut_3_method_3")
        self.runge_kut_4_method_3 = QtWidgets.QRadioButton(self.groupBox_4)
        self.runge_kut_4_method_3.setGeometry(QtCore.QRect(10, 110, 131, 23))
        self.runge_kut_4_method_3.setObjectName("runge_kut_4_method_3")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.tab_5)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 280, 181, 81))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.accuracy_edit_3 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.accuracy_edit_3.setObjectName("accuracy_edit_3")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.accuracy_edit_3)
        self.start_edit_3 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.start_edit_3.setObjectName("start_edit_3")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.start_edit_3)
        self.end_edit_3 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.end_edit_3.setObjectName("end_edit_3")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.end_edit_3)
        self.tab2.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 150, 181, 121))
        self.groupBox_5.setObjectName("groupBox_5")
        self.func_10 = QtWidgets.QRadioButton(self.groupBox_5)
        self.func_10.setGeometry(QtCore.QRect(10, 30, 161, 23))
        self.func_10.setChecked(False)
        self.func_10.setObjectName("func_10")
        self.func_11 = QtWidgets.QRadioButton(self.groupBox_5)
        self.func_11.setGeometry(QtCore.QRect(10, 60, 141, 23))
        self.func_11.setObjectName("func_11")
        self.func_12 = QtWidgets.QRadioButton(self.groupBox_5)
        self.func_12.setGeometry(QtCore.QRect(10, 90, 112, 23))
        self.func_12.setChecked(True)
        self.func_12.setObjectName("func_12")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 10, 181, 141))
        self.groupBox_6.setObjectName("groupBox_6")
        self.euler_method_4 = QtWidgets.QRadioButton(self.groupBox_6)
        self.euler_method_4.setGeometry(QtCore.QRect(10, 20, 112, 23))
        self.euler_method_4.setChecked(False)
        self.euler_method_4.setObjectName("euler_method_4")
        self.ext_euler_method_4 = QtWidgets.QRadioButton(self.groupBox_6)
        self.ext_euler_method_4.setGeometry(QtCore.QRect(10, 50, 112, 23))
        self.ext_euler_method_4.setObjectName("ext_euler_method_4")
        self.runge_kut_3_method_4 = QtWidgets.QRadioButton(self.groupBox_6)
        self.runge_kut_3_method_4.setGeometry(QtCore.QRect(10, 80, 131, 23))
        self.runge_kut_3_method_4.setChecked(True)
        self.runge_kut_3_method_4.setObjectName("runge_kut_3_method_4")
        self.runge_kut_4_method_4 = QtWidgets.QRadioButton(self.groupBox_6)
        self.runge_kut_4_method_4.setGeometry(QtCore.QRect(10, 110, 131, 23))
        self.runge_kut_4_method_4.setObjectName("runge_kut_4_method_4")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.tab_6)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 280, 181, 81))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_4.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_4.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_14.setObjectName("label_14")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_15.setObjectName("label_15")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.accuracy_edit_4 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.accuracy_edit_4.setObjectName("accuracy_edit_4")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.accuracy_edit_4)
        self.start_edit_4 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.start_edit_4.setObjectName("start_edit_4")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.start_edit_4)
        self.end_edit_4 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.end_edit_4.setObjectName("end_edit_4")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.end_edit_4)
        self.tab2.addTab(self.tab_6, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1010, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.tab1.setCurrentIndex(0)
        self.tab2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn.setText(_translate("MainWindow", "Press"))
        self.label_4.setText(_translate("MainWindow", "Result Table:"))
        item = self.result_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "     X     "))
        item = self.result_table.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "     Y     "))
        self.tab1.setTabText(self.tab1.indexOf(self.tab), _translate("MainWindow", "First equitance"))
        item = self.result_table_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "     X     "))
        item = self.result_table_2.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "     Y     "))
        self.label_5.setText(_translate("MainWindow", "Result Table:"))
        self.tab1.setTabText(self.tab1.indexOf(self.tab_2), _translate("MainWindow", "Second equitance"))
        self.label_6.setText(_translate("MainWindow", "Result Table:"))
        item = self.result_table_3.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "     X     "))
        item = self.result_table_3.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "     Y     "))
        self.tab1.setTabText(self.tab1.indexOf(self.tab_3), _translate("MainWindow", "Third equitance"))
        self.groupBox.setTitle(_translate("MainWindow", " Method"))
        self.euler_method.setText(_translate("MainWindow", "Euler"))
        self.ext_euler_method.setText(_translate("MainWindow", "Ext. Euler"))
        self.runge_kut_3_method.setText(_translate("MainWindow", "Runge-Kut 3rd"))
        self.runge_kut_4_method.setText(_translate("MainWindow", "Runge-Kut 4th"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Equitance"))
        self.func_1.setText(_translate("MainWindow", "y\' = 3*x - 2*y + 5"))
        self.func_2.setText(_translate("MainWindow", "y\' = x^2 - y"))
        self.func_3.setText(_translate("MainWindow", "y\' = sin(x)*y"))
        self.label.setText(_translate("MainWindow", "Start:"))
        self.label_2.setText(_translate("MainWindow", "End:"))
        self.label_3.setText(_translate("MainWindow", "Accuracy:"))
        self.accuracy_edit.setText(_translate("MainWindow", "0.1"))
        self.start_edit.setText(_translate("MainWindow", "1"))
        self.end_edit.setText(_translate("MainWindow", "2"))
        self.tab2.setTabText(self.tab2.indexOf(self.tab_4), _translate("MainWindow", "First"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Equitance"))
        self.func_7.setText(_translate("MainWindow", "y\' = 3*x - 2*y + 5"))
        self.func_8.setText(_translate("MainWindow", "y\' = x^2 - y"))
        self.func_9.setText(_translate("MainWindow", "y\' = sin(x)*y"))
        self.groupBox_4.setTitle(_translate("MainWindow", " Method"))
        self.euler_method_3.setText(_translate("MainWindow", "Euler"))
        self.ext_euler_method_3.setText(_translate("MainWindow", "Ext. Euler"))
        self.runge_kut_3_method_3.setText(_translate("MainWindow", "Runge-Kut 3rd"))
        self.runge_kut_4_method_3.setText(_translate("MainWindow", "Runge-Kut 4th"))
        self.label_10.setText(_translate("MainWindow", "Start:"))
        self.label_11.setText(_translate("MainWindow", "End:"))
        self.label_12.setText(_translate("MainWindow", "Accuracy:"))
        self.accuracy_edit_3.setText(_translate("MainWindow", "0.1"))
        self.start_edit_3.setText(_translate("MainWindow", "1"))
        self.end_edit_3.setText(_translate("MainWindow", "2"))
        self.tab2.setTabText(self.tab2.indexOf(self.tab_5), _translate("MainWindow", "Second"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Equitance"))
        self.func_10.setText(_translate("MainWindow", "y\' = 3*x - 2*y + 5"))
        self.func_11.setText(_translate("MainWindow", "y\' = x^2 - y"))
        self.func_12.setText(_translate("MainWindow", "y\' = sin(x)*y"))
        self.groupBox_6.setTitle(_translate("MainWindow", " Method"))
        self.euler_method_4.setText(_translate("MainWindow", "Euler"))
        self.ext_euler_method_4.setText(_translate("MainWindow", "Ext. Euler"))
        self.runge_kut_3_method_4.setText(_translate("MainWindow", "Runge-Kut 3rd"))
        self.runge_kut_4_method_4.setText(_translate("MainWindow", "Runge-Kut 4th"))
        self.label_13.setText(_translate("MainWindow", "Start:"))
        self.label_14.setText(_translate("MainWindow", "End:"))
        self.label_15.setText(_translate("MainWindow", "Accuracy:"))
        self.accuracy_edit_4.setText(_translate("MainWindow", "0.1"))
        self.start_edit_4.setText(_translate("MainWindow", "1"))
        self.end_edit_4.setText(_translate("MainWindow", "2"))
        self.tab2.setTabText(self.tab2.indexOf(self.tab_6), _translate("MainWindow", "Third"))
from pyqtgraph import PlotWidget
