# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 609)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.openGLWidget = CustomGL(self.centralwidget)
        self.openGLWidget.setGeometry(QtCore.QRect(20, 10, 761, 471))
        self.openGLWidget.setObjectName("openGLWidget")
        self.lines_btn = QtWidgets.QPushButton(self.centralwidget)
        self.lines_btn.setGeometry(QtCore.QRect(630, 500, 71, 51))
        self.lines_btn.setCheckable(False)
        self.lines_btn.setObjectName("lines_btn")
        self.dots_btn = QtWidgets.QPushButton(self.centralwidget)
        self.dots_btn.setGeometry(QtCore.QRect(550, 500, 71, 51))
        self.dots_btn.setCheckable(False)
        self.dots_btn.setObjectName("dots_btn")
        self.solid_btn = QtWidgets.QPushButton(self.centralwidget)
        self.solid_btn.setEnabled(False)
        self.solid_btn.setGeometry(QtCore.QRect(710, 500, 71, 51))
        self.solid_btn.setCheckable(False)
        self.solid_btn.setChecked(False)
        self.solid_btn.setObjectName("solid_btn")
        self.piramid_btn = QtWidgets.QPushButton(self.centralwidget)
        self.piramid_btn.setGeometry(QtCore.QRect(20, 500, 81, 51))
        self.piramid_btn.setCheckable(False)
        self.piramid_btn.setObjectName("piramid_btn")
        self.dome_btn = QtWidgets.QPushButton(self.centralwidget)
        self.dome_btn.setEnabled(False)
        self.dome_btn.setGeometry(QtCore.QRect(120, 500, 81, 51))
        self.dome_btn.setCheckable(False)
        self.dome_btn.setChecked(False)
        self.dome_btn.setObjectName("dome_btn")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(220, 500, 321, 56))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.sectors_edit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.sectors_edit.setObjectName("sectors_edit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.sectors_edit)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.error_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.error_label.setText("")
        self.error_label.setAlignment(QtCore.Qt.AlignCenter)
        self.error_label.setObjectName("error_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.error_label)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuword = QtWidgets.QMenu(self.menubar)
        self.menuword.setObjectName("menuword")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionWord = QtWidgets.QAction(MainWindow)
        self.actionWord.setObjectName("actionWord")
        self.actionExcel = QtWidgets.QAction(MainWindow)
        self.actionExcel.setObjectName("actionExcel")
        self.actionHel = QtWidgets.QAction(MainWindow)
        self.actionHel.setObjectName("actionHel")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuword.addAction(self.actionWord)
        self.menuword.addAction(self.actionExcel)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionExit)
        self.menubar.addAction(self.menuword.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Курсовая работа"))
        self.lines_btn.setText(_translate("MainWindow", "Lines"))
        self.dots_btn.setText(_translate("MainWindow", "Dots"))
        self.solid_btn.setText(_translate("MainWindow", "Solid"))
        self.piramid_btn.setText(_translate("MainWindow", "Piramid"))
        self.dome_btn.setText(_translate("MainWindow", "Dome"))
        self.label_2.setText(_translate("MainWindow", "Sectors"))
        self.menuword.setTitle(_translate("MainWindow", "Save"))
        self.menuHelp.setTitle(_translate("MainWindow", "Options"))
        self.actionWord.setText(_translate("MainWindow", "Word"))
        self.actionExcel.setText(_translate("MainWindow", "Excel"))
        self.actionHel.setText(_translate("MainWindow", "Hel["))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
from custom_gl import CustomGL
