# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'blueprint.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(969, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = PlotWidget(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(205, 20, 761, 421))
        self.graphicsView.setObjectName("graphicsView")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 181, 151))
        self.groupBox.setObjectName("groupBox")
        self.euler_method = QtWidgets.QRadioButton(self.groupBox)
        self.euler_method.setGeometry(QtCore.QRect(10, 30, 112, 23))
        self.euler_method.setChecked(True)
        self.euler_method.setObjectName("euler_method")
        self.ext_euler_method = QtWidgets.QRadioButton(self.groupBox)
        self.ext_euler_method.setGeometry(QtCore.QRect(10, 60, 112, 23))
        self.ext_euler_method.setObjectName("ext_euler_method")
        self.runge_kut_3_method = QtWidgets.QRadioButton(self.groupBox)
        self.runge_kut_3_method.setGeometry(QtCore.QRect(10, 90, 131, 23))
        self.runge_kut_3_method.setObjectName("runge_kut_3_method")
        self.runge_kut_4_method = QtWidgets.QRadioButton(self.groupBox)
        self.runge_kut_4_method.setGeometry(QtCore.QRect(10, 120, 131, 23))
        self.runge_kut_4_method.setObjectName("runge_kut_4_method")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 180, 181, 121))
        self.groupBox_2.setObjectName("groupBox_2")
        self.func_1 = QtWidgets.QRadioButton(self.groupBox_2)
        self.func_1.setGeometry(QtCore.QRect(10, 30, 161, 23))
        self.func_1.setChecked(True)
        self.func_1.setObjectName("func_1")
        self.func_2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.func_2.setGeometry(QtCore.QRect(10, 60, 141, 23))
        self.func_2.setObjectName("func_2")
        self.func_3 = QtWidgets.QRadioButton(self.groupBox_2)
        self.func_3.setGeometry(QtCore.QRect(10, 90, 112, 23))
        self.func_3.setObjectName("func_3")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 310, 181, 89))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.accuracy_edit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.accuracy_edit.setObjectName("accuracy_edit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.accuracy_edit)
        self.end_edit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.end_edit.setObjectName("end_edit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.end_edit)
        self.start_edit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.start_edit.setObjectName("start_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.start_edit)
        self.btn = QtWidgets.QPushButton(self.centralwidget)
        self.btn.setGeometry(QtCore.QRect(10, 400, 181, 41))
        self.btn.setObjectName("btn")
        self.result_table = QtWidgets.QTableWidget(self.centralwidget)
        self.result_table.setGeometry(QtCore.QRect(10, 490, 951, 171))
        self.result_table.setObjectName("result_table")
        self.result_table.setColumnCount(0)
        self.result_table.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.result_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.result_table.setVerticalHeaderItem(1, item)
        self.result_table.horizontalHeader().setMinimumSectionSize(57)
        self.result_table.verticalHeader().setDefaultSectionSize(57)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 460, 261, 17))
        self.label_4.setObjectName("label_4")
        self.word_btn = QtWidgets.QPushButton(self.centralwidget)
        self.word_btn.setGeometry(QtCore.QRect(798, 450, 161, 25))
        self.word_btn.setObjectName("word_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 969, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", " Method"))
        self.euler_method.setText(_translate("MainWindow", "Euler"))
        self.ext_euler_method.setText(_translate("MainWindow", "Ext. Euler"))
        self.runge_kut_3_method.setText(_translate("MainWindow", "Runge-Kut 3rd"))
        self.runge_kut_4_method.setText(_translate("MainWindow", "Runge-Kut 4th"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Equitance"))
        self.func_1.setText(_translate("MainWindow", "y\' = 3*x - 2*y + 5"))
        self.func_2.setText(_translate("MainWindow", "y\' = x^2 - y"))
        self.func_3.setText(_translate("MainWindow", "y\' = sin(x)*y"))
        self.label.setText(_translate("MainWindow", "Start:"))
        self.label_2.setText(_translate("MainWindow", "End:"))
        self.label_3.setText(_translate("MainWindow", "Accuracy:"))
        self.accuracy_edit.setText(_translate("MainWindow", "0.1"))
        self.end_edit.setText(_translate("MainWindow", "2"))
        self.start_edit.setText(_translate("MainWindow", "1"))
        self.btn.setText(_translate("MainWindow", "Press"))
        item = self.result_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "     X     "))
        item = self.result_table.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "     Y     "))
        self.label_4.setText(_translate("MainWindow", "Result Table:"))
        self.word_btn.setText(_translate("MainWindow", "Excel"))
from pyqtgraph import PlotWidget
