# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'controller/blueprint.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1167, 672)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 441, 521))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 421, 71))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 403, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.functions_1 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.functions_1.setContentsMargins(0, 0, 0, 0)
        self.functions_1.setObjectName("functions_1")
        self.first_function_1 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.first_function_1.setChecked(True)
        self.first_function_1.setObjectName("first_function_1")
        self.functions_1.addWidget(self.first_function_1)
        self.second_function_1 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.second_function_1.setObjectName("second_function_1")
        self.functions_1.addWidget(self.second_function_1)
        self.third_function_1 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.third_function_1.setObjectName("third_function_1")
        self.functions_1.addWidget(self.third_function_1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 90, 421, 251))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 401, 211))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.methods_1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.methods_1.setContentsMargins(0, 0, 0, 0)
        self.methods_1.setObjectName("methods_1")
        self.trapeze_1 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.trapeze_1.setChecked(True)
        self.trapeze_1.setObjectName("trapeze_1")
        self.methods_1.addWidget(self.trapeze_1)
        self.left_1 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.left_1.setObjectName("left_1")
        self.methods_1.addWidget(self.left_1)
        self.right_1 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.right_1.setObjectName("right_1")
        self.methods_1.addWidget(self.right_1)
        self.mid_1 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.mid_1.setObjectName("mid_1")
        self.methods_1.addWidget(self.mid_1)
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 350, 421, 131))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.low_1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.low_1.setObjectName("low_1")
        self.gridLayout.addWidget(self.low_1, 1, 0, 1, 1)
        self.high_1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.high_1.setObjectName("high_1")
        self.gridLayout.addWidget(self.high_1, 1, 1, 1, 1)
        self.step_1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.step_1.setObjectName("step_1")
        self.gridLayout.addWidget(self.step_1, 1, 2, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 90, 421, 251))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 401, 211))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.methods_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.methods_2.setContentsMargins(0, 0, 0, 0)
        self.methods_2.setObjectName("methods_2")
        self.trapeze_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.trapeze_2.setChecked(False)
        self.trapeze_2.setObjectName("trapeze_2")
        self.methods_2.addWidget(self.trapeze_2)
        self.left_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.left_2.setChecked(True)
        self.left_2.setObjectName("left_2")
        self.methods_2.addWidget(self.left_2)
        self.right_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.right_2.setObjectName("right_2")
        self.methods_2.addWidget(self.right_2)
        self.mid_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.mid_2.setObjectName("mid_2")
        self.methods_2.addWidget(self.mid_2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 10, 421, 71))
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_4)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 30, 403, 31))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.functions_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.functions_2.setContentsMargins(0, 0, 0, 0)
        self.functions_2.setObjectName("functions_2")
        self.first_function_2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_4)
        self.first_function_2.setChecked(False)
        self.first_function_2.setObjectName("first_function_2")
        self.functions_2.addWidget(self.first_function_2)
        self.second_function_2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_4)
        self.second_function_2.setChecked(True)
        self.second_function_2.setObjectName("second_function_2")
        self.functions_2.addWidget(self.second_function_2)
        self.third_function_2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_4)
        self.third_function_2.setObjectName("third_function_2")
        self.functions_2.addWidget(self.third_function_2)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 350, 421, 131))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 2, 1, 1)
        self.low_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.low_2.setObjectName("low_2")
        self.gridLayout_2.addWidget(self.low_2, 1, 0, 1, 1)
        self.high_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.high_2.setObjectName("high_2")
        self.gridLayout_2.addWidget(self.high_2, 1, 1, 1, 1)
        self.step_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.step_2.setObjectName("step_2")
        self.gridLayout_2.addWidget(self.step_2, 1, 2, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(480, 500, 661, 120))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_3.addWidget(self.lineEdit_7, 0, 1, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_3.addWidget(self.lineEdit_8, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 3, 0, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_3.addWidget(self.lineEdit_9, 2, 1, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_3.addWidget(self.lineEdit_10, 3, 1, 1, 1)
        self.graphicsView = PlotWidget(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(480, 40, 661, 441))
        self.graphicsView.setObjectName("graphicsView")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(70, 540, 311, 71))
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1167, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Подынтегральная функция"))
        self.first_function_1.setText(_translate("MainWindow", "sin(x)/sqrt(x)"))
        self.second_function_1.setText(_translate("MainWindow", "cos(pi*x/6)/sqrt(x)"))
        self.third_function_1.setText(_translate("MainWindow", "1/(1 + sin^3(x))"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Метод вычисления"))
        self.trapeze_1.setText(_translate("MainWindow", "Метод трапеции"))
        self.left_1.setText(_translate("MainWindow", "Метод левых прямоугольников"))
        self.right_1.setText(_translate("MainWindow", "Метод правых прямоугольников"))
        self.mid_1.setText(_translate("MainWindow", "Метод средних прямоугольников"))
        self.label_2.setText(_translate("MainWindow", "Верхний предел:"))
        self.label.setText(_translate("MainWindow", "Нижний предел:"))
        self.label_3.setText(_translate("MainWindow", "Шаг:"))
        self.low_1.setText(_translate("MainWindow", "1"))
        self.high_1.setText(_translate("MainWindow", "2"))
        self.step_1.setText(_translate("MainWindow", "0.1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Первый интеграл"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Метод вычисления"))
        self.trapeze_2.setText(_translate("MainWindow", "Метод трапеции"))
        self.left_2.setText(_translate("MainWindow", "Метод левых прямоугольников"))
        self.right_2.setText(_translate("MainWindow", "Метод правых прямоугольников"))
        self.mid_2.setText(_translate("MainWindow", "Метод средних прямоугольников"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Подынтегральная функция"))
        self.first_function_2.setText(_translate("MainWindow", "sin(x)/sqrt(x)"))
        self.second_function_2.setText(_translate("MainWindow", "cos(pi*x/6)/sqrt(x)"))
        self.third_function_2.setText(_translate("MainWindow", "1/(1 + sin^3(x))"))
        self.label_4.setText(_translate("MainWindow", "Верхний предел:"))
        self.label_5.setText(_translate("MainWindow", "Нижний предел:"))
        self.label_6.setText(_translate("MainWindow", "Шаг:"))
        self.low_2.setText(_translate("MainWindow", "1.5"))
        self.high_2.setText(_translate("MainWindow", "2.5"))
        self.step_2.setText(_translate("MainWindow", "0.1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Второй интеграл"))
        self.lineEdit_7.setText(_translate("MainWindow", "0"))
        self.lineEdit_8.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "Первый интеграл"))
        self.label_9.setText(_translate("MainWindow", "Сумма"))
        self.label_8.setText(_translate("MainWindow", "Второй интеграл"))
        self.label_10.setText(_translate("MainWindow", "Разность"))
        self.lineEdit_9.setText(_translate("MainWindow", "0"))
        self.lineEdit_10.setText(_translate("MainWindow", "0"))
        self.pushButton_2.setText(_translate("MainWindow", "Вычислить"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
